development:
    dialect: sqlite3
    datasource: lyfeed_development.db
    dir: migrations/sqlite
    table: migrations

production:
    dialect: sqlite3
    datasource: lyfeed_prod.db
    dir: migrations/sqlite
    table: migrations
